[package]
name = "btc-vanity"
version = "1.2.1"
authors = ["Emirhan TALA <emirhantala99ff99@gmail.com>"]
description = "A bitcoin vanity address generator written with the Rust programming language."
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Emivvvvv/btc-vanity"
documentation = "https://docs.rs/btc-vanity/latest/btc_vanity/index.html"


[dependencies]
rand = "0.8.5"
bitcoin = { version = "0.32.2", features = ["rand-std"] }
thiserror = "1.0.63"
clap = "4.5.16"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"

[profile.test]
opt-level = 3
