[package]
name = "btc-vanity"
version = "1.3.0"
authors = ["Emirhan TALA <tala.emirhan@gmail.com>"]
description = "A bitcoin vanity address generator written with the Rust programming language."
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Emivvvvv/btc-vanity"
documentation = "https://docs.rs/btc-vanity/latest/btc_vanity/index.html"


[dependencies]
rand = "0.9.0-alpha.2"
bitcoin = { version = "0.32.3", features = ["rand-std"] }
thiserror = "1.0.64"
clap = "4.5.20"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"

[profile.test]
opt-level = 3

[features]
test_only = []
