name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get update && sudo apt-get install -y build-essential perl make

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install strawberryperl make

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install perl make

      - name: Add Rust target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build with vendored OpenSSL
        run: |
          cargo build --release --features "vendored"
          cargo dist build --output-format=json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: target/release

  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: artifacts

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release of ${{ github.ref_name }}" \
            artifacts/*
