name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "solana", "ethereum", "all"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings # Check with all features

      - name: Build and Test with Features - ${{ matrix.features }}
        run: |
          cargo build --verbose ${{ matrix.features && format('--features {0}', matrix.features) || '' }}
          cargo test --verbose ${{ matrix.features && format('--features {0}', matrix.features) || '' }}

      - name: Run doc tests with all features
        run: cargo test --doc --all-features